# Generated by Django 4.1.3 on 2023-02-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orc',
            options={'verbose_name': 'Орки в деревне', 'verbose_name_plural': 'Орки в деревне'},
        ),
        migrations.AlterField(
            model_name='orc',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='orc',
            name='tags',
            field=models.ManyToManyField(related_name='orcs', to='main.tag'),
        ),
    ]
