# Generated by Django 4.1.3 on 2023-02-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_alter_orc_options_alter_orc_title_orc_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Теги', 'verbose_name_plural': 'Теги'},
        ),
    ]
