# Generated by Django 4.1.3 on 2023-02-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_remove_orc_tags_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Der',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Деревни',
                'verbose_name_plural': 'Деревни',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='orc',
            name='der',
            field=models.ManyToManyField(related_name='orcs', to='main.der'),
        ),
    ]
